# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
