# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='aa',
        ),
        migrations.AddField(
            model_name='environment',
            name='humidity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='wind_direction',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='wind_speed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
