# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160120_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='question_text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
