# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_environment_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='question_text',
            new_name='product_name',
        ),
    ]
